"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['PySweeper.py']
DATA_FILES = [
    ('', ['images']),
]
OPTIONS = {
    'packages': ['PIL'], # For some reason, py2app doesn't include the whole PIL, which leads to _tkinter_finder.py being missing, which is apparently required...
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
